spring:
  application:
    name: gamerecs-back
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        # Memory optimizations
        jdbc.batch_size: 30
        order_inserts: true
        order_updates: true
        generate_statistics: false
        # Cache settings
        cache:
          use_second_level_cache: false
          use_query_cache: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: true
    validate-on-migrate: true
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# Server Configuration
server:
  port: ${PORT:8080}
  tomcat:
    max-threads: 20
    min-spare-threads: 5
    max-connections: 100
    accept-count: 50
    connection-timeout: 5000
    max-swallow-size: 2MB
    max-http-form-post-size: 2MB

# CORS Configuration
allowed:
  origins: ${ALLOWED_ORIGINS:http://localhost:4200}

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

# Application specific configuration
app:
  verification:
    base-url: ${VERIFICATION_BASE_URL:http://localhost:4200}
    token:
      expiration-hours: 24  # Token expiration time in hours
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}  # 24 hours in milliseconds
