# Required metadata
sonar.projectKey=GameRecs
sonar.organization=gamerecs

# Source code location
sonar.sources=gamerecs-front/src,gamerecs-back/src/main
sonar.tests=gamerecs-front/src/app/**/*.spec.ts,gamerecs-back/src/test

# Language
sonar.language=ts,java
sonar.typescript.lcov.reportPaths=gamerecs-front/coverage/lcov.info
sonar.java.binaries=gamerecs-back/target/classes
sonar.java.test.binaries=gamerecs-back/target/test-classes
sonar.java.libraries=gamerecs-back/target/dependency/*.jar

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclude
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/dist/**,**/coverage/**,**/target/** 