name: Backend CI/CD

on:
  push:
    branches: [ main, develop, 'feature-*' ]
    paths:
      - 'gamerecs-back/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'gamerecs-back/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./gamerecs-back

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package -DskipTests
      
    - name: Run Tests
      run: mvn -B test -Dspring.profiles.active=test

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Run SonarCloud Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn -B verify sonar:sonar \
        -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
        -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
        -Dsonar.java.coveragePlugin=jacoco \
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
        -Dsonar.qualitygate.wait=true

    - name: Build and Push Docker Image
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker build -t $DOCKER_USERNAME/gamerecs-back:${GITHUB_REF##*/} .
        docker push $DOCKER_USERNAME/gamerecs-back:${GITHUB_REF##*/}

    - name: Heroku Login
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
  
    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/main'
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:push web -a gamer-reco
        heroku container:release web -a gamer-reco
  
    - name: Deploy to Heroku Staging
      if: github.ref == 'refs/heads/develop'
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:push web -a gamer-reco-staging
        heroku container:release web -a gamer-reco-staging
